# Generated by Django 2.0.6 on 2018-06-25 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sa',
            new_name='security_answer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sq',
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question',
            field=models.TextField(choices=[('1', 'Best friends name'), ('2', 'Favourite food'), ('3', "Pet's name")], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
