# Generated by Django 2.0.6 on 2018-06-25 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180625_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bd',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
