# Generated by Django 2.0.6 on 2018-06-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180627_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fname',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lname',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phoneno',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sa',
            field=models.CharField(max_length=10, verbose_name='Security Answer'),
        ),
    ]
