# Generated by Django 2.0.6 on 2018-06-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180629_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profpic',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
