# Generated by Django 2.0.6 on 2018-06-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180629_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profpic',
        ),
    ]
