# Generated by Django 2.0.6 on 2018-06-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_profpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profpic',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fname',
            field=models.CharField(blank=True, max_length=10, verbose_name='First Name'),
        ),
    ]
