# Generated by Django 2.0.6 on 2018-07-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180702_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='birth_certificate',
            field=models.FileField(default=False, upload_to='documents%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='marksheet',
            field=models.FileField(default=False, upload_to='documents%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='resume',
            field=models.FileField(default=False, upload_to='documents%Y%m%d'),
        ),
    ]
